from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutPageWindow(object):
    def setupUi(self, AboutPageWindow):
        AboutPageWindow.setObjectName("AboutPageWindow")
        AboutPageWindow.resize(667, 401)
        AboutPageWindow.setMinimumSize(QtCore.QSize(667, 401))
        AboutPageWindow.setMaximumSize(QtCore.QSize(667, 401))
        AboutPageWindow.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.centralwidget = QtWidgets.QWidget(AboutPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 50, 471, 321))
        # self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame_2.setMouseTracking(False)
        self.frame_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-top-color:2px green;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border:2px rgb(207, 207, 207);")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.back_btn = QtWidgets.QPushButton(self.frame_2)
        self.back_btn.setGeometry(QtCore.QRect(180, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(190, 30, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.creator = QtWidgets.QLabel(self.centralwidget)
        self.creator.setGeometry(QtCore.QRect(580, 350, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.creator.setFont(font)
        self.creator.setStyleSheet("border: 2px rgb(207, 207, 207);")
        self.creator.setObjectName("creator")
        AboutPageWindow.setCentralWidget(self.centralwidget)
        self.statusbar_of_aboutpage = QtWidgets.QStatusBar(AboutPageWindow)
        self.statusbar_of_aboutpage.setObjectName("statusbar_of_aboutpage")
        AboutPageWindow.setStatusBar(self.statusbar_of_aboutpage)
        self.actionOpenFile = QtWidgets.QAction(AboutPageWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(AboutPageWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(AboutPageWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutPageWindow)

    def retranslateUi(self, AboutPageWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutPageWindow.setWindowTitle(_translate("AboutPageWindow", "MainWindow"))
        self.label.setText(_translate("AboutPageWindow", "PAUDIO"))
        self.back_btn.setStatusTip(_translate("AboutPageWindow", "Close"))
        self.back_btn.setText(_translate("AboutPageWindow", "Back"))
        self.label_3.setText(_translate("AboutPageWindow", "The"))
        self.label_4.setText(_translate("AboutPageWindow", "is a audio book made by a Praveenkumar."))
        self.creator.setStatusTip(_translate("AboutPageWindow", "Creator"))
        self.creator.setText(_translate("AboutPageWindow", "PraveeKumar"))
        self.actionOpenFile.setText(_translate("AboutPageWindow", "OpenFile"))
        self.actionClose.setText(_translate("AboutPageWindow", "Close"))
