from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailsPageWindow(object):
    def setupUi(self, DetailsPageWindow):
        DetailsPageWindow.setObjectName("DetailsPageWindow")
        DetailsPageWindow.resize(667, 401)
        DetailsPageWindow.setMinimumSize(QtCore.QSize(667, 401))
        DetailsPageWindow.setMaximumSize(QtCore.QSize(667, 401))
        DetailsPageWindow.setStyleSheet("border-color:20px green;\n"
"background-color:rgb(207, 207, 207);\n"
"")
        self.centralwidget = QtWidgets.QWidget(DetailsPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 50, 471, 321))
        # self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setMouseTracking(False)
        self.frame_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-top-color:2px green;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(20, 10, 421, 241))
        # self.frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame.setMouseTracking(False)
        self.frame.setStyleSheet("\n"
"border-color:20px green;\n"
"background-color:rgb(207, 207, 207);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.SelectedFile_lb = QtWidgets.QLabel(self.frame)
        self.SelectedFile_lb.setGeometry(QtCore.QRect(11, 21, 92, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SelectedFile_lb.setFont(font)
        self.SelectedFile_lb.setObjectName("SelectedFile_lb")
        self.File_name_lb = QtWidgets.QLabel(self.frame)
        self.File_name_lb.setGeometry(QtCore.QRect(110, 23, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.File_name_lb.setFont(font)
        self.File_name_lb.setObjectName("File_name_lb")
        self.TotalPage_lb = QtWidgets.QLabel(self.frame)
        self.TotalPage_lb.setGeometry(QtCore.QRect(10, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TotalPage_lb.setFont(font)
        self.TotalPage_lb.setObjectName("TotalPage_lb")
        self.SelectPage_lb = QtWidgets.QLabel(self.frame)
        self.SelectPage_lb.setGeometry(QtCore.QRect(20, 160, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SelectPage_lb.setFont(font)
        self.SelectPage_lb.setObjectName("SelectPage_lb")
        self.availablePages_lb = QtWidgets.QLabel(self.frame)
        self.availablePages_lb.setGeometry(QtCore.QRect(130, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.availablePages_lb.setFont(font)
        self.availablePages_lb.setObjectName("availablePages_lb")
        self.From_pages = QtWidgets.QLineEdit(self.frame)
        self.From_pages.setGeometry(QtCore.QRect(150, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setBold(True)
        font.setWeight(75)
        self.From_pages.setFont(font)
        self.From_pages.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.From_pages.setAutoFillBackground(False)
        self.From_pages.setStyleSheet("background-color: rgb(207, 207, 230);")
        self.From_pages.setFrame(False)
        self.From_pages.setObjectName("From_pages")
        self.To_pages = QtWidgets.QLineEdit(self.frame)
        self.To_pages.setGeometry(QtCore.QRect(260, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setBold(True)
        font.setWeight(75)
        self.To_pages.setFont(font)
        self.To_pages.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.To_pages.setAutoFillBackground(False)
        self.To_pages.setStyleSheet("background-color: rgb(207, 207, 230);")
        self.To_pages.setFrame(False)
        self.To_pages.setObjectName("To_pages")
        self.back_btn = QtWidgets.QPushButton(self.frame_2)
        self.back_btn.setGeometry(QtCore.QRect(340, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.Start_btn = QtWidgets.QPushButton(self.frame_2)
        self.Start_btn.setGeometry(QtCore.QRect(30, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Start_btn.setFont(font)
        self.Start_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.Start_btn.setObjectName("Start_btn")
        self.creator = QtWidgets.QLabel(self.centralwidget)
        self.creator.setGeometry(QtCore.QRect(590, 350, 71, 21))
        self.creator.setStyleSheet("border: 2px rgb(207, 207, 207);")
        self.creator.setObjectName("creator")
        self.title_lb = QtWidgets.QLabel(self.centralwidget)
        self.title_lb.setGeometry(QtCore.QRect(110, 10, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title_lb.setFont(font)
        # self.title_lb.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title_lb.setStyleSheet("border:2px rgb(207, 207, 207);")
        self.title_lb.setTextFormat(QtCore.Qt.PlainText)
        self.title_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lb.setObjectName("title_lb")
        DetailsPageWindow.setCentralWidget(self.centralwidget)
        self.statusbar_of_listenpage = QtWidgets.QStatusBar(DetailsPageWindow)
        self.statusbar_of_listenpage.setObjectName("statusbar_of_listenpage")
        DetailsPageWindow.setStatusBar(self.statusbar_of_listenpage)
        self.actionOpenFile = QtWidgets.QAction(DetailsPageWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(DetailsPageWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(DetailsPageWindow)
        QtCore.QMetaObject.connectSlotsByName(DetailsPageWindow)

    def retranslateUi(self, DetailsPageWindow):
        _translate = QtCore.QCoreApplication.translate
        DetailsPageWindow.setWindowTitle(_translate("DetailsPageWindow", "MainWindow"))
        self.SelectedFile_lb.setText(_translate("DetailsPageWindow", "Selected File :"))
        self.File_name_lb.setStatusTip(_translate("DetailsPageWindow", "File Name"))
        self.File_name_lb.setText(_translate("DetailsPageWindow", "xyz file"))
        self.TotalPage_lb.setText(_translate("DetailsPageWindow", "Total Pages :"))
        self.SelectPage_lb.setText(_translate("DetailsPageWindow", "Select Pages :"))
        self.availablePages_lb.setStatusTip(_translate("DetailsPageWindow", "Total Pages Available"))
        self.availablePages_lb.setText(_translate("DetailsPageWindow", "99999999999999999999"))
        self.From_pages.setStatusTip(_translate("DetailsPageWindow", "Select Page Number"))
        self.From_pages.setText(_translate("DetailsPageWindow", "From"))
        self.To_pages.setStatusTip(_translate("DetailsPageWindow", "Last Page Number"))
        self.To_pages.setText(_translate("DetailsPageWindow", "To"))
        self.back_btn.setStatusTip(_translate("DetailsPageWindow", "Go back"))
        self.back_btn.setText(_translate("DetailsPageWindow", "BACK"))
        self.Start_btn.setStatusTip(_translate("DetailsPageWindow", "Lets Start"))
        self.Start_btn.setWhatsThis(_translate("DetailsPageWindow", "Start saying"))
        self.Start_btn.setText(_translate("DetailsPageWindow", "START"))
        self.creator.setStatusTip(_translate("DetailsPageWindow", "Creator"))
        self.creator.setText(_translate("DetailsPageWindow", "PraveeKumar"))
        self.title_lb.setText(_translate("DetailsPageWindow", "PAUDIO"))
        self.actionOpenFile.setText(_translate("DetailsPageWindow", "OpenFile"))
        self.actionClose.setText(_translate("DetailsPageWindow", "Close"))
