from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrontPageWindow(object):
    def setupUi(self, FrontPageWindow):
        FrontPageWindow.setObjectName("FrontPageWindow")
        FrontPageWindow.resize(667, 401)
        FrontPageWindow.setMinimumSize(QtCore.QSize(667, 401))
        FrontPageWindow.setMaximumSize(QtCore.QSize(667, 401))
        FrontPageWindow.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.centralwidget = QtWidgets.QWidget(FrontPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 50, 471, 321))
        # self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame_2.setMouseTracking(False)
        self.frame_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-top-color:2px green;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(70, 130, 331, 191))
        # self.frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame.setMouseTracking(False)
        self.frame.setStyleSheet("\n"
"border-color:20px green;\n"
"background-color:rgb(207, 207, 207);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.start_btn = QtWidgets.QPushButton(self.frame)
        self.start_btn.setGeometry(QtCore.QRect(110, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.start_btn.setObjectName("start_btn")
        self.about_btn = QtWidgets.QPushButton(self.frame)
        self.about_btn.setGeometry(QtCore.QRect(110, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.about_btn.setFont(font)
        self.about_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;")
        self.about_btn.setObjectName("about_btn")
        self.close_btn = QtWidgets.QPushButton(self.frame)
        self.close_btn.setGeometry(QtCore.QRect(110, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.close_btn.setObjectName("close_btn")
        self.title = QtWidgets.QLabel(self.frame_2)
        self.title.setGeometry(QtCore.QRect(10, 30, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("border:2px rgb(207, 207, 207);")
        self.title.setTextFormat(QtCore.Qt.PlainText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.creator = QtWidgets.QLabel(self.centralwidget)
        self.creator.setGeometry(QtCore.QRect(590, 350, 71, 21))
        self.creator.setStyleSheet("border: 2px rgb(207, 207, 207);")
        self.creator.setObjectName("creator")
        FrontPageWindow.setCentralWidget(self.centralwidget)
        self.statusbar_of_frontpage = QtWidgets.QStatusBar(FrontPageWindow)
        self.statusbar_of_frontpage.setObjectName("statusbar_of_frontpage")
        FrontPageWindow.setStatusBar(self.statusbar_of_frontpage)
        self.actionOpenFile = QtWidgets.QAction(FrontPageWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(FrontPageWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(FrontPageWindow)
        QtCore.QMetaObject.connectSlotsByName(FrontPageWindow)

    def retranslateUi(self, FrontPageWindow):
        _translate = QtCore.QCoreApplication.translate
        FrontPageWindow.setWindowTitle(_translate("FrontPageWindow", "MainWindow"))
        self.start_btn.setStatusTip(_translate("FrontPageWindow", "start"))
        self.start_btn.setWhatsThis(_translate("FrontPageWindow", "Lets Go"))
        self.start_btn.setText(_translate("FrontPageWindow", "START"))
        self.about_btn.setStatusTip(_translate("FrontPageWindow", "About"))
        self.about_btn.setText(_translate("FrontPageWindow", "ABOUT"))
        self.close_btn.setStatusTip(_translate("FrontPageWindow", "Close"))
        self.close_btn.setText(_translate("FrontPageWindow", "CLOSE"))
        self.title.setText(_translate("FrontPageWindow", "PAUDIO"))
        self.creator.setStatusTip(_translate("FrontPageWindow", "Creator"))
        self.creator.setText(_translate("FrontPageWindow", "PraveeKumar"))
        self.actionOpenFile.setText(_translate("FrontPageWindow", "OpenFile"))
        self.actionClose.setText(_translate("FrontPageWindow", "Close"))
