# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Listenpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListenPageWindow(object):
    def setupUi(self, ListenPageWindow):
        ListenPageWindow.setObjectName("ListenPageWindow")
        ListenPageWindow.resize(667, 401)
        ListenPageWindow.setMinimumSize(QtCore.QSize(667, 401))
        ListenPageWindow.setMaximumSize(QtCore.QSize(667, 401))
        ListenPageWindow.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.centralwidget = QtWidgets.QWidget(ListenPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 50, 471, 321))
        # self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setMouseTracking(False)
        self.frame_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-top-color:2px green;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(20, 80, 421, 241))
        # self.frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame.setMouseTracking(False)
        self.frame.setStyleSheet("\n"
"border-color:20px green;\n"
"background-color:rgb(207, 207, 207);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 401, 231))
        self.plainTextEdit.setOverwriteMode(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        font=QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.stop_btn = QtWidgets.QPushButton(self.frame_2)
        self.stop_btn.setGeometry(QtCore.QRect(10, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.stop_btn.setObjectName("stop_btn")
        self.back_btn = QtWidgets.QPushButton(self.frame_2)
        self.back_btn.setGeometry(QtCore.QRect(340, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.listen_btn = QtWidgets.QPushButton(self.frame_2)
        self.listen_btn.setGeometry(QtCore.QRect(170, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.listen_btn.setFont(font)
        self.listen_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.listen_btn.setObjectName("listen_btn")
        self.creator = QtWidgets.QLabel(self.centralwidget)
        self.creator.setGeometry(QtCore.QRect(590, 350, 71, 21))
        self.creator.setStyleSheet("border: 2px rgb(207, 207, 207);")
        self.creator.setObjectName("creator")
        self.title_lb = QtWidgets.QLabel(self.centralwidget)
        self.title_lb.setGeometry(QtCore.QRect(110, 10, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title_lb.setFont(font)
        # self.title_lb.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title_lb.setStyleSheet("border:2px rgb(207, 207, 207);")
        self.title_lb.setTextFormat(QtCore.Qt.PlainText)
        self.title_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lb.setObjectName("title_lb")
        ListenPageWindow.setCentralWidget(self.centralwidget)
        self.statusbar_of_listenpage = QtWidgets.QStatusBar(ListenPageWindow)
        self.statusbar_of_listenpage.setObjectName("statusbar_of_listenpage")
        ListenPageWindow.setStatusBar(self.statusbar_of_listenpage)
        self.actionOpenFile = QtWidgets.QAction(ListenPageWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(ListenPageWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(ListenPageWindow)
        QtCore.QMetaObject.connectSlotsByName(ListenPageWindow)

    def retranslateUi(self, ListenPageWindow):
        _translate = QtCore.QCoreApplication.translate
        ListenPageWindow.setWindowTitle(_translate("ListenPageWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("ListenPageWindow", "Your reading text will appear here"))
        self.stop_btn.setStatusTip(_translate("ListenPageWindow", "stop"))
        self.stop_btn.setWhatsThis(_translate("ListenPageWindow", "stop saying"))
        self.stop_btn.setText(_translate("ListenPageWindow", "STOP"))
        self.back_btn.setStatusTip(_translate("ListenPageWindow", "Go back"))
        self.back_btn.setText(_translate("ListenPageWindow", "BACK"))
        self.listen_btn.setStatusTip(_translate("ListenPageWindow", "Listen"))
        self.listen_btn.setWhatsThis(_translate("ListenPageWindow", "Continue listening"))
        self.listen_btn.setText(_translate("ListenPageWindow", "LISTEN"))
        self.creator.setStatusTip(_translate("ListenPageWindow", "Creator"))
        self.creator.setText(_translate("ListenPageWindow", "PraveeKumar"))
        self.title_lb.setText(_translate("ListenPageWindow", "PAUDIO"))
        self.actionOpenFile.setText(_translate("ListenPageWindow", "OpenFile"))
        self.actionClose.setText(_translate("ListenPageWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ListenPageWindow = QtWidgets.QMainWindow()
    ui = Ui_ListenPageWindow()
    ui.setupUi(ListenPageWindow)
    ListenPageWindow.show()
    sys.exit(app.exec_())
