from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartPageWindow(object):
    def setupUi(self, StartPageWindow):
        StartPageWindow.setObjectName("StartPageWindow")
        StartPageWindow.resize(667, 401)
        StartPageWindow.setMinimumSize(QtCore.QSize(667, 401))
        StartPageWindow.setMaximumSize(QtCore.QSize(667, 401))
        StartPageWindow.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.centralwidget = QtWidgets.QWidget(StartPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 50, 471, 321))
        # self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame_2.setMouseTracking(False)
        self.frame_2.setStyleSheet("background-color: rgb(207, 207, 207);\n"
"border-top-color:2px green;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(70, 130, 331, 191))
        # self.frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame.setMouseTracking(False)
        self.frame.setStyleSheet("\n"
"border-color:20px green;\n"
"background-color:rgb(207, 207, 207);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.select_btn = QtWidgets.QPushButton(self.frame)
        self.select_btn.setGeometry(QtCore.QRect(110, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.select_btn.setFont(font)
        self.select_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.select_btn.setObjectName("select_btn")
        self.back_btn = QtWidgets.QPushButton(self.frame)
        self.back_btn.setGeometry(QtCore.QRect(110, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.listen_btn = QtWidgets.QPushButton(self.frame)
        self.listen_btn.setGeometry(QtCore.QRect(110, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.listen_btn.setFont(font)
        self.listen_btn.setStyleSheet("border:2px solid green;\n"
"border-radius:20px;\n"
"")
        self.listen_btn.setObjectName("listen_btn")
        self.title = QtWidgets.QLabel(self.frame_2)
        self.title.setGeometry(QtCore.QRect(10, 30, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("border:2px rgb(207, 207, 207);")
        self.title.setTextFormat(QtCore.Qt.PlainText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.creator = QtWidgets.QLabel(self.centralwidget)
        self.creator.setGeometry(QtCore.QRect(590, 350, 71, 21))
        self.creator.setStyleSheet("border: 2px rgb(207, 207, 207);")
        self.creator.setObjectName("creator")
        StartPageWindow.setCentralWidget(self.centralwidget)
        self.statusbar_of_startpage = QtWidgets.QStatusBar(StartPageWindow)
        self.statusbar_of_startpage.setObjectName("statusbar_of_startpage")
        StartPageWindow.setStatusBar(self.statusbar_of_startpage)
        self.actionOpenFile = QtWidgets.QAction(StartPageWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(StartPageWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(StartPageWindow)
        QtCore.QMetaObject.connectSlotsByName(StartPageWindow)

    def retranslateUi(self, StartPageWindow):
        _translate = QtCore.QCoreApplication.translate
        StartPageWindow.setWindowTitle(_translate("StartPageWindow", "MainWindow"))
        self.select_btn.setStatusTip(_translate("StartPageWindow", "Select file"))
        self.select_btn.setWhatsThis(_translate("StartPageWindow", "Lets Go"))
        self.select_btn.setText(_translate("StartPageWindow", "SELECT"))
        self.back_btn.setStatusTip(_translate("StartPageWindow", "Go back"))
        self.back_btn.setText(_translate("StartPageWindow", "BACK"))
        self.listen_btn.setStatusTip(_translate("StartPageWindow", "Listen to the selected file"))
        self.listen_btn.setWhatsThis(_translate("StartPageWindow", "Lets Go"))
        self.listen_btn.setText(_translate("StartPageWindow", "LISTEN"))
        self.title.setText(_translate("StartPageWindow", "PAUDIO"))
        self.creator.setStatusTip(_translate("StartPageWindow", "Creator"))
        self.creator.setText(_translate("StartPageWindow", "PraveeKumar"))
        self.actionOpenFile.setText(_translate("StartPageWindow", "OpenFile"))
        self.actionClose.setText(_translate("StartPageWindow", "Close"))

